runtime: nodejs18
env_variables:
  API_URL: "https://taskmanagement-system.ew.r.appspot.com"
handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|css|png|jpe?g|gif|svg|woff2?|eot|ttf|otf))$
    static_files: build/\1
    upload: build/(.*)(\.(json|ico|js|css|png|jpe?g|gif|svg|woff2?|eot|ttf|otf))$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
